### PR TITLE
Added Solution to Query 23

### PR DESCRIPTION
**Pull request by sagar-monga**
Solves Issue #50

### CODE REVIEW

**Comment by sagar-monga** [comment]
Whoops. I can't delete it now. Can you please remove the config file and merge the PR? 😄

**Comment by sagar-monga** [comment]
@priithaa kindly merge.

**Comment by ananya0504** [comment]
HI @sagar-monga 
Request you to pls remove the `setting.json` file that you've added.

**Review by ananya0504 — CHANGES_REQUESTED** [review]
Please remove the settings.json file!

**Comment by sagar-monga** [comment]
@ananya0504 I am closing this and will raise new PR with the changes. Unable to edit this PR.

Raised PR [#128](https://github.com/LeanIn-BV/HacktoberFest2021/pull/128) for the same. 
Kindly Review

**Pull request closed without merging**
