### PR TITLE
Solved Query: 7

### PR DESCRIPTION
**Pull request by renaiku**
Solving #12

### CODE REVIEW

**Review by ananya0504 — CHANGES_REQUESTED** [review]
Please rename the folder and file according to the format.

**Comment by renaiku** [comment]
**You propose in this repo 3 different name format:**
- [in this query 42 file](https://github.com/LeanIn-BV/HacktoberFest2021/blob/main/Problems/Query-42/Query-42.md), I should rename as `Query-7`
- [in this Issue_Name file](https://github.com/LeanIn-BV/HacktoberFest2021/blob/main/Problems/Issue_Name), I should rename as `Query_7`
- [in this Contributing.md file](https://github.com/LeanIn-BV/HacktoberFest2021/blob/main/Contributing.md) I should rename as `Query-7`.

Wich one of your 3 proposition should I use ?

**Comment by renaiku** [comment]
@ananya0504  Done !

I chose to follow the Contributing.md file format. I hope It's the good one.

Can you create an issue to rename [this file](https://github.com/LeanIn-BV/HacktoberFest2021/blob/main/Problems/Issue_Name) and assign it to me please ? I will rename it `Problmes/Query-Number/Query-Number.md` ?

If yes, can you make it part of the hacktober fest please ?

**Review by ananya0504 — APPROVED** [review]
Looks good now, thanks!

**Comment by ananya0504** [comment]
> @ananya0504 Done !
> 
> I chose to follow the Contributing.md file format. I hope It's the good one.
> 
> Can you create an issue to rename [this file](https://github.com/LeanIn-BV/HacktoberFest2021/blob/main/Problems/Issue_Name) and assign it to me please ? I will rename it `Problmes/Query-Number/Query-Number.md` ?
> 
> If yes, can you make it part of the hacktober fest please ?

PRs related to renaming files won't be counted for HacktoberFest!

**Pull request closed without merging**
